/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RPLXPBO;

/**
 *
 * @author ASUS
 */
public class Article extends javax.swing.JFrame {

    /**
     * Creates new form Article
     */
    public Article() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Footer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NavbarNotLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        MostViewArticle1 = new javax.swing.JButton();
        titleArticle = new javax.swing.JLabel();
        tagArticle = new javax.swing.JLabel();
        IsiArtikel = new javax.swing.JLabel();
        authorArticle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        MostViewArticle2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        authorArticle1 = new javax.swing.JLabel();
        IsiArtikel1 = new javax.swing.JLabel();
        titleArticle1 = new javax.swing.JLabel();
        tagArticle1 = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        MostViewArticle3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        authorArticle2 = new javax.swing.JLabel();
        IsiArtikel2 = new javax.swing.JLabel();
        titleArticle2 = new javax.swing.JLabel();
        tagArticle2 = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        MostViewArticle4 = new javax.swing.JButton();
        titleArticle3 = new javax.swing.JLabel();
        tagArticle3 = new javax.swing.JLabel();
        IsiArtikel3 = new javax.swing.JLabel();
        authorArticle3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        MostViewArticle5 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        authorArticle4 = new javax.swing.JLabel();
        IsiArtikel4 = new javax.swing.JLabel();
        titleArticle4 = new javax.swing.JLabel();
        tagArticle4 = new javax.swing.JLabel();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        MostViewArticle6 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        authorArticle5 = new javax.swing.JLabel();
        IsiArtikel5 = new javax.swing.JLabel();
        titleArticle5 = new javax.swing.JLabel();
        tagArticle5 = new javax.swing.JLabel();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        MostViewArticle7 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        authorArticle6 = new javax.swing.JLabel();
        IsiArtikel6 = new javax.swing.JLabel();
        titleArticle6 = new javax.swing.JLabel();
        tagArticle6 = new javax.swing.JLabel();
        jLayeredPane11 = new javax.swing.JLayeredPane();
        MostViewArticle8 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        authorArticle7 = new javax.swing.JLabel();
        IsiArtikel7 = new javax.swing.JLabel();
        titleArticle7 = new javax.swing.JLabel();
        tagArticle7 = new javax.swing.JLabel();
        jLayeredPane12 = new javax.swing.JLayeredPane();
        MostViewArticle9 = new javax.swing.JButton();
        titleArticle8 = new javax.swing.JLabel();
        tagArticle8 = new javax.swing.JLabel();
        IsiArtikel8 = new javax.swing.JLabel();
        authorArticle8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 2235));
        setMinimumSize(new java.awt.Dimension(1440, 795));
        setSize(new java.awt.Dimension(1440, 2235));

        Footer.setBackground(new java.awt.Color(252, 246, 246));
        Footer.setPreferredSize(new java.awt.Dimension(1440, 76));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\FooterLeft.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\FooterRight.png")); // NOI18N

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 647, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(135, 135, 135))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24))
        );

        NavbarNotLogin.setBackground(new java.awt.Color(253, 80, 126));
        NavbarNotLogin.setPreferredSize(new java.awt.Dimension(1440, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\Logo(White).png")); // NOI18N

        jButton1.setContentAreaFilled(false);
        SignUpButton.setBackground(new java.awt.Color(253, 80, 126));
        SignUpButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\SingUpButton.png")); // NOI18N
        SignUpButton.setBorder(null);

        jButton1.setContentAreaFilled(false);
        jButton1.setBackground(new java.awt.Color(253, 80, 126));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\SingInButton.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavbarNotLoginLayout = new javax.swing.GroupLayout(NavbarNotLogin);
        NavbarNotLogin.setLayout(NavbarNotLoginLayout);
        NavbarNotLoginLayout.setHorizontalGroup(
            NavbarNotLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarNotLoginLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(SignUpButton)
                .addGap(135, 135, 135))
        );
        NavbarNotLoginLayout.setVerticalGroup(
            NavbarNotLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarNotLoginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(NavbarNotLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NavbarNotLoginLayout.createSequentialGroup()
                        .addComponent(SignUpButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1440, 32767));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1441, 2045));

        jPanel1.setBackground(new java.awt.Color(252, 246, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 2044));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Article");

        jLayeredPane4.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane4.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-1.png"))); // NOI18N
        MostViewArticle1.setBorder(null);

        titleArticle.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle.setText("The Power of Make Up");

        tagArticle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle.setText("BEAUTY");

        IsiArtikel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        authorArticle.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle.setText("by Tasya Farasya");

        jSeparator2.setBackground(new java.awt.Color(230, 230, 230));

        jLayeredPane4.setLayer(MostViewArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(titleArticle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(tagArticle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(IsiArtikel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(authorArticle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IsiArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(titleArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tagArticle)
                            .addComponent(MostViewArticle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle1)
                .addGap(21, 21, 21)
                .addComponent(tagArticle)
                .addGap(15, 15, 15)
                .addComponent(titleArticle)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel)
                .addGap(55, 55, 55)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLayeredPane5.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane5.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-2.png"))); // NOI18N
        MostViewArticle2.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle1.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle1.setText("by Tasya Farasya");

        IsiArtikel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel1.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel1.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle1.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle1.setText("The Power of Make Up");

        tagArticle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle1.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle1.setText("BEAUTY");

        jLayeredPane5.setLayer(MostViewArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(authorArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(IsiArtikel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(titleArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(tagArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MostViewArticle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorArticle1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IsiArtikel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleArticle1)
                    .addComponent(tagArticle1)
                    .addComponent(jSeparator3))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle2)
                .addGap(21, 21, 21)
                .addComponent(tagArticle1)
                .addGap(15, 15, 15)
                .addComponent(titleArticle1)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel1)
                .addGap(55, 55, 55)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane6.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane6.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-3.png"))); // NOI18N
        MostViewArticle3.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle2.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle2.setText("by Tasya Farasya");

        IsiArtikel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel2.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel2.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle2.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle2.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle2.setText("The Power of Make Up");

        tagArticle2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle2.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle2.setText("BEAUTY");

        jLayeredPane6.setLayer(MostViewArticle3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(authorArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(IsiArtikel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(titleArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(tagArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorArticle2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IsiArtikel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleArticle2)
                            .addComponent(tagArticle2))
                        .addGap(90, 90, 90))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MostViewArticle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle3)
                .addGap(21, 21, 21)
                .addComponent(tagArticle2)
                .addGap(15, 15, 15)
                .addComponent(titleArticle2)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel2)
                .addGap(55, 55, 55)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane7.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane7.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-1.png"))); // NOI18N
        MostViewArticle4.setBorder(null);

        titleArticle3.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle3.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle3.setText("The Power of Make Up");

        tagArticle3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle3.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle3.setText("BEAUTY");

        IsiArtikel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel3.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel3.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        authorArticle3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle3.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle3.setText("by Tasya Farasya");

        jSeparator5.setBackground(new java.awt.Color(230, 230, 230));

        jLayeredPane7.setLayer(MostViewArticle4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(titleArticle3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(tagArticle3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(IsiArtikel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(authorArticle3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IsiArtikel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(titleArticle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tagArticle3)
                            .addComponent(MostViewArticle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorArticle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle4)
                .addGap(21, 21, 21)
                .addComponent(tagArticle3)
                .addGap(15, 15, 15)
                .addComponent(titleArticle3)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel3)
                .addGap(55, 55, 55)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLayeredPane8.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane8.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-3.png"))); // NOI18N
        MostViewArticle5.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle4.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle4.setText("by Tasya Farasya");

        IsiArtikel4.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel4.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel4.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle4.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle4.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle4.setText("The Power of Make Up");

        tagArticle4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle4.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle4.setText("BEAUTY");

        jLayeredPane8.setLayer(MostViewArticle5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(authorArticle4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(IsiArtikel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(titleArticle4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(tagArticle4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane8Layout.createSequentialGroup()
                        .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorArticle4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IsiArtikel4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleArticle4)
                            .addComponent(tagArticle4))
                        .addGap(102, 102, 102))
                    .addGroup(jLayeredPane8Layout.createSequentialGroup()
                        .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostViewArticle5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle5)
                .addGap(21, 21, 21)
                .addComponent(tagArticle4)
                .addGap(15, 15, 15)
                .addComponent(titleArticle4)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel4)
                .addGap(55, 55, 55)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane9.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane9.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-2.png"))); // NOI18N
        MostViewArticle6.setBorder(null);

        jSeparator7.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle5.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle5.setText("by Tasya Farasya");

        IsiArtikel5.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel5.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel5.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle5.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle5.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle5.setText("The Power of Make Up");

        tagArticle5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle5.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle5.setText("BEAUTY");

        jLayeredPane9.setLayer(MostViewArticle6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(authorArticle5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(IsiArtikel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(titleArticle5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane9.setLayer(tagArticle5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
        jLayeredPane9.setLayout(jLayeredPane9Layout);
        jLayeredPane9Layout.setHorizontalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MostViewArticle6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorArticle5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IsiArtikel5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleArticle5)
                    .addComponent(tagArticle5)
                    .addComponent(jSeparator7))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane9Layout.setVerticalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle6)
                .addGap(21, 21, 21)
                .addComponent(tagArticle5)
                .addGap(15, 15, 15)
                .addComponent(titleArticle5)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel5)
                .addGap(55, 55, 55)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane10.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane10.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-2.png"))); // NOI18N
        MostViewArticle7.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle6.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle6.setText("by Tasya Farasya");

        IsiArtikel6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel6.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel6.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle6.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle6.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle6.setText("The Power of Make Up");

        tagArticle6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle6.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle6.setText("BEAUTY");

        jLayeredPane10.setLayer(MostViewArticle7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(authorArticle6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(IsiArtikel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(titleArticle6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(tagArticle6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane10Layout = new javax.swing.GroupLayout(jLayeredPane10);
        jLayeredPane10.setLayout(jLayeredPane10Layout);
        jLayeredPane10Layout.setHorizontalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MostViewArticle7)
                        .addComponent(authorArticle6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IsiArtikel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(titleArticle6)
                        .addComponent(tagArticle6)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane10Layout.setVerticalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle7)
                .addGap(21, 21, 21)
                .addComponent(tagArticle6)
                .addGap(15, 15, 15)
                .addComponent(titleArticle6)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel6)
                .addGap(55, 55, 55)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane11.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane11.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-3.png"))); // NOI18N
        MostViewArticle8.setBorder(null);

        jSeparator9.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle7.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle7.setText("by Tasya Farasya");

        IsiArtikel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel7.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel7.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle7.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle7.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle7.setText("The Power of Make Up");

        tagArticle7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle7.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle7.setText("BEAUTY");

        jLayeredPane11.setLayer(MostViewArticle8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(authorArticle7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(IsiArtikel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(titleArticle7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(tagArticle7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane11Layout = new javax.swing.GroupLayout(jLayeredPane11);
        jLayeredPane11.setLayout(jLayeredPane11Layout);
        jLayeredPane11Layout.setHorizontalGroup(
            jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane11Layout.createSequentialGroup()
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorArticle7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IsiArtikel7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleArticle7)
                            .addComponent(tagArticle7))
                        .addGap(102, 102, 102))
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostViewArticle8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jLayeredPane11Layout.setVerticalGroup(
            jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle8)
                .addGap(21, 21, 21)
                .addComponent(tagArticle7)
                .addGap(15, 15, 15)
                .addComponent(titleArticle7)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel7)
                .addGap(55, 55, 55)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane12.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane12.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-1.png"))); // NOI18N
        MostViewArticle9.setBorder(null);

        titleArticle8.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle8.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle8.setText("The Power of Make Up");

        tagArticle8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle8.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle8.setText("BEAUTY");

        IsiArtikel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel8.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel8.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        authorArticle8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle8.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle8.setText("by Tasya Farasya");

        jSeparator10.setBackground(new java.awt.Color(230, 230, 230));

        jLayeredPane12.setLayer(MostViewArticle9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane12.setLayer(titleArticle8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane12.setLayer(tagArticle8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane12.setLayer(IsiArtikel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane12.setLayer(authorArticle8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane12.setLayer(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane12Layout = new javax.swing.GroupLayout(jLayeredPane12);
        jLayeredPane12.setLayout(jLayeredPane12Layout);
        jLayeredPane12Layout.setHorizontalGroup(
            jLayeredPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jLayeredPane12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IsiArtikel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(titleArticle8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tagArticle8)
                    .addComponent(MostViewArticle9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorArticle8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane12Layout.setVerticalGroup(
            jLayeredPane12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle9)
                .addGap(21, 21, 21)
                .addComponent(tagArticle8)
                .addGap(15, 15, 15)
                .addComponent(titleArticle8)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel8)
                .addGap(55, 55, 55)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton2.setContentAreaFilled(false);
        jButton6.setBackground(new java.awt.Color(252, 246, 246));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/ButtonArrowleft.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setContentAreaFilled(false);
        jButton7.setBackground(new java.awt.Color(252, 246, 246));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/ButtonArrowRight.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(253, 80, 126));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("1");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray));
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(252, 246, 246));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setText("2");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray));
        jButton3.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(252, 246, 246));
        jButton4.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 153, 153));
        jButton4.setText("4");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray));
        jButton4.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(252, 246, 246));
        jButton5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 153, 153));
        jButton5.setText("3");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray));
        jButton5.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(636, 636, 636)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLayeredPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLayeredPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLayeredPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(15, 15, 15)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton7)
                .addGap(598, 598, 598))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Footer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE)
                        .addComponent(NavbarNotLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavbarNotLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Article.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Article().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JLabel IsiArtikel;
    private javax.swing.JLabel IsiArtikel1;
    private javax.swing.JLabel IsiArtikel2;
    private javax.swing.JLabel IsiArtikel3;
    private javax.swing.JLabel IsiArtikel4;
    private javax.swing.JLabel IsiArtikel5;
    private javax.swing.JLabel IsiArtikel6;
    private javax.swing.JLabel IsiArtikel7;
    private javax.swing.JLabel IsiArtikel8;
    private javax.swing.JButton MostViewArticle1;
    private javax.swing.JButton MostViewArticle2;
    private javax.swing.JButton MostViewArticle3;
    private javax.swing.JButton MostViewArticle4;
    private javax.swing.JButton MostViewArticle5;
    private javax.swing.JButton MostViewArticle6;
    private javax.swing.JButton MostViewArticle7;
    private javax.swing.JButton MostViewArticle8;
    private javax.swing.JButton MostViewArticle9;
    private javax.swing.JPanel NavbarNotLogin;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel authorArticle;
    private javax.swing.JLabel authorArticle1;
    private javax.swing.JLabel authorArticle2;
    private javax.swing.JLabel authorArticle3;
    private javax.swing.JLabel authorArticle4;
    private javax.swing.JLabel authorArticle5;
    private javax.swing.JLabel authorArticle6;
    private javax.swing.JLabel authorArticle7;
    private javax.swing.JLabel authorArticle8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane11;
    private javax.swing.JLayeredPane jLayeredPane12;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel tagArticle;
    private javax.swing.JLabel tagArticle1;
    private javax.swing.JLabel tagArticle2;
    private javax.swing.JLabel tagArticle3;
    private javax.swing.JLabel tagArticle4;
    private javax.swing.JLabel tagArticle5;
    private javax.swing.JLabel tagArticle6;
    private javax.swing.JLabel tagArticle7;
    private javax.swing.JLabel tagArticle8;
    private javax.swing.JLabel titleArticle;
    private javax.swing.JLabel titleArticle1;
    private javax.swing.JLabel titleArticle2;
    private javax.swing.JLabel titleArticle3;
    private javax.swing.JLabel titleArticle4;
    private javax.swing.JLabel titleArticle5;
    private javax.swing.JLabel titleArticle6;
    private javax.swing.JLabel titleArticle7;
    private javax.swing.JLabel titleArticle8;
    // End of variables declaration//GEN-END:variables
}
