/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RPLXPBO;

/**
 *
 * @author ASUS
 */
public class DetailArticle extends javax.swing.JFrame {

    /**
     * Creates new form DetailArticle
     */
    public DetailArticle() {
        initComponents();
        titleArticle.setText("The Power Of Make Up");
        dateArticle.setText("28 October 2023");
        authorArticle.setText("Tasya Farasya");
        IsiArtikel.setText("Lorem ipsum Lorem ipsum");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavbarLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        titleArticle = new javax.swing.JLabel();
        dateArticle = new javax.swing.JLabel();
        authorArticle = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pictureArticle = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        IsiArtikel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 2309));

        NavbarLogin.setBackground(new java.awt.Color(253, 80, 126));
        NavbarLogin.setPreferredSize(new java.awt.Dimension(1440, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\Logo(White).png")); // NOI18N

        javax.swing.GroupLayout NavbarLoginLayout = new javax.swing.GroupLayout(NavbarLogin);
        NavbarLogin.setLayout(NavbarLoginLayout);
        NavbarLoginLayout.setHorizontalGroup(
            NavbarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLoginLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addContainerGap(1152, Short.MAX_VALUE))
        );
        NavbarLoginLayout.setVerticalGroup(
            NavbarLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLoginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(NavbarLogin, java.awt.BorderLayout.PAGE_START);

        Footer.setBackground(new java.awt.Color(252, 246, 246));
        Footer.setPreferredSize(new java.awt.Dimension(1440, 76));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\FooterLeft.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\FooterRight.png")); // NOI18N

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 644, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(135, 135, 135))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24))
        );

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(252, 246, 246));

        BackButton.setContentAreaFilled(false);
        BackButton.setBackground(new java.awt.Color(252, 246, 246));
        BackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\ButtonBack.png")); // NOI18N
        BackButton.setBorder(null);

        titleArticle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleArticle.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle.setText("Lorem Ipsum");

        dateArticle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dateArticle.setForeground(new java.awt.Color(253, 80, 126));
        dateArticle.setText("DD/MM/YY");

        authorArticle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        authorArticle.setForeground(new java.awt.Color(253, 80, 126));
        authorArticle.setText("Lorem Ipsum");

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\Ellipse.png")); // NOI18N

        pictureArticle.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\PhotoArticle1.png")); // NOI18N
        pictureArticle.setName(""); // NOI18N
        pictureArticle.setPreferredSize(null);

        IsiArtikel.setText("jLabel1");
        IsiArtikel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateArticle)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(authorArticle))
                            .addComponent(titleArticle)
                            .addComponent(pictureArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IsiArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(BackButton)
                .addGap(70, 70, 70)
                .addComponent(titleArticle)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateArticle)
                    .addComponent(authorArticle)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pictureArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IsiArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1429, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailArticle().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Footer;
    private javax.swing.JLabel IsiArtikel;
    private javax.swing.JPanel NavbarLogin;
    private javax.swing.JLabel authorArticle;
    private javax.swing.JLabel dateArticle;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel pictureArticle;
    private javax.swing.JLabel titleArticle;
    // End of variables declaration//GEN-END:variables
}
