/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RPLXPBO;

/**
 *
 * @author ASUS
 */
public class LandingPageIfNotLogin extends javax.swing.JFrame {

    /**
     * Creates new form LandingPageIfNotLogin
     */
    public LandingPageIfNotLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavbarNotLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Footer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        MostViewArticle1 = new javax.swing.JButton();
        titleArticle = new javax.swing.JLabel();
        tagArticle = new javax.swing.JLabel();
        IsiArtikel = new javax.swing.JLabel();
        authorArticle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        MostViewArticle2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        authorArticle1 = new javax.swing.JLabel();
        IsiArtikel1 = new javax.swing.JLabel();
        titleArticle1 = new javax.swing.JLabel();
        tagArticle1 = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        MostViewArticle3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        authorArticle2 = new javax.swing.JLabel();
        IsiArtikel2 = new javax.swing.JLabel();
        titleArticle2 = new javax.swing.JLabel();
        tagArticle2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1440, 962));

        NavbarNotLogin.setBackground(new java.awt.Color(253, 80, 126));
        NavbarNotLogin.setPreferredSize(new java.awt.Dimension(1440, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\Logo(White).png")); // NOI18N

        jButton1.setContentAreaFilled(false);
        SignUpButton.setBackground(new java.awt.Color(253, 80, 126));
        SignUpButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\SingUpButton.png")); // NOI18N
        SignUpButton.setBorder(null);

        jButton1.setContentAreaFilled(false);
        jButton1.setBackground(new java.awt.Color(253, 80, 126));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\SingInButton.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavbarNotLoginLayout = new javax.swing.GroupLayout(NavbarNotLogin);
        NavbarNotLogin.setLayout(NavbarNotLoginLayout);
        NavbarNotLoginLayout.setHorizontalGroup(
            NavbarNotLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarNotLoginLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 808, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(SignUpButton)
                .addGap(135, 135, 135))
        );
        NavbarNotLoginLayout.setVerticalGroup(
            NavbarNotLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarNotLoginLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(NavbarNotLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(NavbarNotLoginLayout.createSequentialGroup()
                        .addComponent(SignUpButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        getContentPane().add(NavbarNotLogin, java.awt.BorderLayout.PAGE_START);

        Footer.setBackground(new java.awt.Color(252, 246, 246));
        Footer.setPreferredSize(new java.awt.Dimension(1440, 76));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\FooterLeft.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\FooterRight.png")); // NOI18N

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 644, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(135, 135, 135))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24))
        );

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(252, 246, 246));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 806));

        jButton1.setContentAreaFilled(false);
        jButton3.setBackground(new java.awt.Color(252, 246, 246));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\Tel-U\\Kuliah\\Semester 5\\RPLXPBO\\SeeAllButton.png")); // NOI18N
        jButton3.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Top 3 Most View Article");

        jLayeredPane4.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane4.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-1.png"))); // NOI18N
        MostViewArticle1.setBorder(null);

        titleArticle.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle.setText("The Power of Make Up");

        tagArticle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle.setText("BEAUTY");

        IsiArtikel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        authorArticle.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle.setText("by Tasya Farasya");

        jSeparator2.setBackground(new java.awt.Color(230, 230, 230));

        jLayeredPane4.setLayer(MostViewArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(titleArticle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(tagArticle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(IsiArtikel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(authorArticle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IsiArtikel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(titleArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tagArticle)
                            .addComponent(MostViewArticle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(authorArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle1)
                .addGap(21, 21, 21)
                .addComponent(tagArticle)
                .addGap(15, 15, 15)
                .addComponent(titleArticle)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel)
                .addGap(55, 55, 55)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane5.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane5.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-2.png"))); // NOI18N
        MostViewArticle2.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle1.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle1.setText("by Tasya Farasya");

        IsiArtikel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel1.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel1.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle1.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle1.setText("The Power of Make Up");

        tagArticle1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle1.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle1.setText("BEAUTY");

        jLayeredPane5.setLayer(MostViewArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(authorArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(IsiArtikel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(titleArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(tagArticle1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(MostViewArticle2))
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(authorArticle1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(IsiArtikel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(titleArticle1))
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(tagArticle1))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle2)
                .addGap(21, 21, 21)
                .addComponent(tagArticle1)
                .addGap(15, 15, 15)
                .addComponent(titleArticle1)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel1)
                .addGap(55, 55, 55)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLayeredPane6.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLayeredPane6.setMaximumSize(new java.awt.Dimension(1000, 1000));

        MostViewArticle3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPLXPBO/PhotoArticle-3.png"))); // NOI18N
        MostViewArticle3.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(230, 230, 230));

        authorArticle2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        authorArticle2.setForeground(new java.awt.Color(0, 0, 0));
        authorArticle2.setText("by Tasya Farasya");

        IsiArtikel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        IsiArtikel2.setForeground(new java.awt.Color(0, 0, 0));
        IsiArtikel2.setText("Lorem ipsum dolor sit amet, elite consectetur adipiscing, sed do eiusmod...");

        titleArticle2.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        titleArticle2.setForeground(new java.awt.Color(0, 0, 0));
        titleArticle2.setText("The Power of Make Up");

        tagArticle2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tagArticle2.setForeground(new java.awt.Color(253, 80, 126));
        tagArticle2.setText("BEAUTY");

        jLayeredPane6.setLayer(MostViewArticle3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(authorArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(IsiArtikel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(titleArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(tagArticle2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorArticle2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IsiArtikel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleArticle2)
                            .addComponent(tagArticle2))
                        .addGap(102, 102, 102))
                    .addGroup(jLayeredPane6Layout.createSequentialGroup()
                        .addGroup(jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostViewArticle3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MostViewArticle3)
                .addGap(21, 21, 21)
                .addComponent(tagArticle2)
                .addGap(15, 15, 15)
                .addComponent(titleArticle2)
                .addGap(15, 15, 15)
                .addComponent(IsiArtikel2)
                .addGap(55, 55, 55)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorArticle2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(434, 434, 434))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(611, 611, 611))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(jButton3)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPageIfNotLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPageIfNotLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPageIfNotLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPageIfNotLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPageIfNotLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JLabel IsiArtikel;
    private javax.swing.JLabel IsiArtikel1;
    private javax.swing.JLabel IsiArtikel2;
    private javax.swing.JButton MostViewArticle1;
    private javax.swing.JButton MostViewArticle2;
    private javax.swing.JButton MostViewArticle3;
    private javax.swing.JPanel NavbarNotLogin;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel authorArticle;
    private javax.swing.JLabel authorArticle1;
    private javax.swing.JLabel authorArticle2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel tagArticle;
    private javax.swing.JLabel tagArticle1;
    private javax.swing.JLabel tagArticle2;
    private javax.swing.JLabel titleArticle;
    private javax.swing.JLabel titleArticle1;
    private javax.swing.JLabel titleArticle2;
    // End of variables declaration//GEN-END:variables
}
